### ISSUE TITLE
[BUG] When SPEAKER is enabled in custom builds, it will make initial sound on start, but beeps will stop working later

### ISSUE THREAD

**Issue by SargeR33** [mriscoc/Ender3V2S1#1094] opened 2023-09-16 11:00 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Very strange. I was running an August release with no issues at all. Ender 3 v2 with 4.2.2 ret6 and a DACAI screen. Screen previously flashed with DACAI firmware, all working correctly.

Since updating to latest release with a custom build, the internal speaker will make its initial double beep on startup. It will work like normal until the system executes another double beep, it makes a odd double beep sound and then the speaker will stop working. It will no longer beep when navigating the menu and clicking with single beeps.

Its nit picky yes but, strange behavior. 

### Bug Timeline

After latest FW build and update.

### Expected behavior

Single beep while navigating through menu, double beep for store and other specific functions. 

### Actual behavior

Odd sounding double beep which will cause the speaker to no longer work until the machine is rebooted. It will however still produce double beeps that almost sound like they clip.

### Steps to Reproduce

Turn printer on, 50 50 chance the speaker will immediately stop. If it does not stop, going into any menu and hitting store settings has so far produced 100% situation where speaker will no longer work while navigating the menus. Speaker was enabled in FW build.

### Version of Professional Firmware

20230904 

### Printer model

Ender 3 V2

### Electronics

4.2.2 RET6

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment] 2023-09-18 13:48
Tested in precompiled
![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/4902d6ec-1e5d-43bb-9c91-e382e1b1c2de)
I can't reproduce the issue.

**Comment by Crazy-Charles** [comment] 2023-09-20 19:06
Can confirm that i have same issue on my custom builds with speaker enabled, straight after re-flashing and entering a menu it produces a single bleep when the encoder is pressed but as soon as i "save settings" the single bleep ceases to work, double bleeps still work ok

**Comment by Crazy-Charles** [comment] 2023-09-20 19:38
As a quick work around, change encoder.cpp to use buzzer.tone(duration, frequency), i used 50ms and 1000Hz, instead of buzzer.click(10)

**Comment by SargeR33** [comment] 2023-09-23 07:25
My mistake. I did NOT use a precompiled build. It was custom builds.

**Comment by mriscoc** [comment] 2023-12-18 05:45
Fixed in the latest ANNIVERSARY 2023 version

**Closed as completed by mriscoc** 2023-12-18 05:45 UTC
Labels: bug: Confirmed
