### ISSUE TITLE
[BUG] display showing weird artifacts

### ISSUE THREAD

**Issue by tonysprenk** [mriscoc/Ender3V2S1#1246] opened 2024-02-04 10:48 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Since the latest update I’m seeing weird artifacts on the display (see image). Can this be solved by updating the firmware of the display? Or is it more likely to be hardware issue?

### Version of Professional Firmware

20240122

### Printer model

Ender 3v2

### Electronics

4.2.2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

![IMG_0584](https://github.com/mriscoc/Ender3V2S1/assets/38426377/1146690d-ad18-416d-af06-a9e5334cd338)

**Comment by Abasz** [comment] 2024-02-09 11:59
I have something similar. It starts after the printer is on for a long time:
![20240208_195802](https://github.com/mriscoc/Ender3V2S1/assets/32517724/424cb500-0274-4148-b668-b8fbb4963309)
These are random artifacts that start to appear.

I have skr mini e3v3 with the cable mod.

**Comment by DBNinja** [comment] 2024-02-16 23:49
I'd like to also +1 this issue. I only noticed this after the printer was on for several days and after 6+ 3 hour prints (I wasn't paying attention to when this happened). 

Details about my setup:

Ender 3v2 with 4.2.2 board, T5 
Version 2.1.3 MRiscoC
Custom Build with Configurator. Options enabled: BLT - UBL - DWIN - T5 - IS - LA - MPC - Speaker
RE_creality environment. 

![IMG_20240216_135032](https://github.com/mriscoc/Ender3V2S1/assets/6099303/d68e0ed5-d0cc-4935-b3ae-64e5ba292e4b)

UBL Mesh was 10x10. IS was not changed from default.

All prints via octoprint (print from octoprint).

Does not seem to impact printing.

**Comment by mriscoc** [comment] 2024-02-17 04:07
Duplicate of: https://github.com/mriscoc/Ender3V2S1/issues/749, https://github.com/mriscoc/Ender3V2S1/issues/558, https://github.com/mriscoc/Ender3V2S1/issues/359, https://github.com/mriscoc/Ender3V2S1/issues/328, etc.

**Closed as completed** 2024-02-26 00:50 UTC
Labels: duplicate
