### ISSUE TITLE
UI Artifacts (enlarged numerical text) on Print Status Screen

### ISSUE THREAD

**Issue by derekpock** [mriscoc/Ender3V2S1#558] opened 2022-12-18 10:33 UTC
When starting a print, there are visual artifacts in the UI that appear to be enlarged numbers that render partially on the bottom of the screen and partially on the top of the screen. See the attached images for details.

**Preconditions**
- Ender 3 V2 with 4.2.7 board (although I'm certain I saw this on 4.2.2 prior to my upgrade as well)
- Firmware version: Ender3V2-427-BLT-20221002.bin (or if 4.2.2, was running Ender3V2-422-BLT-20221002.bin)
- CRTouch - Recently ran Tramming, ABL, and calibrated Z level

(no other modifications beyond stock Ender 3 V2)

**Steps to reproduce the behavior:**
1. Load CalibrationCube.gcode onto SD card. This was built with Cura 5.2.1 with the Jpeg gcode preview plugin installed and used. Other prints caused this too, may not be gcode specific.
2. Preheat nozzle to 205 and bed to 60.
3. Print CalibrationCube.gcode.
4. Wait a few moments for bed to warm, nozzle to heat, and print to start.
5. Observe UI artifacts as described and seen in attached pictures.

**Notes:**
- Navigating a menu will clear the upper artifacts.
- Shutting off the LCD (and bringing back up) will clear the lower artifacts.
- I believe this appears near the start of the print, during or soon after the nozzle heating gcode, but I haven't confirmed this.
- I had a hard time reproducing this - saw it occasionally (out of maybe 8 prints, saw it 3 times?). Might try reproducing more.

**Files**
CalibartionCube.gcode (zipped) that was being printed while the artifacts appeared
[CalibrationCube.zip](https://github.com/mriscoc/Ender3V2S1/files/10253607/CalibrationCube.zip)

**Screenshots**
UI artifacts shown during print:
<img src="https://user-images.githubusercontent.com/6723267/208293688-3abcf24f-acca-4def-9dfa-ea95074e62ad.jpg" width="300"/>

Upper artifacts cleared when navigating to "Tune" menu:
<img src="https://user-images.githubusercontent.com/6723267/208293703-12154a3f-6bc6-40d0-8dfc-c20de6ae797c.jpg" width="300"/>

More info on the "Tune" page if that helps reproduce things:
<img src="https://user-images.githubusercontent.com/6723267/208293732-a8f5b81d-46a8-4bb3-b653-edd4053e2d86.jpg" width="300"/>

Lower artifacts cleared after blanking and re-showing the LCD screen:
<img src="https://user-images.githubusercontent.com/6723267/208293758-cb0d9c46-4cda-45cc-8e9a-7ffddf78c6ad.jpg" width="300"/>

Printer setup (default Ender 3 V2 with 4.2.7 board and CRTouch):
<img src="https://user-images.githubusercontent.com/6723267/208293780-ec285dd6-57d4-48d8-9d4c-58c3beab9fba.jpg" width="300"/>

**Comment by mriscoc** [comment] 2022-12-19 04:32
Duplicate of: https://github.com/mriscoc/Ender3V2S1/issues/359 and https://github.com/mriscoc/Ender3V2S1/issues/328

**Closed as completed by mriscoc** 2022-12-19 04:32 UTC
Labels: duplicate, known issue
