### ISSUE TITLE
Setting multi probe to 1 causes probing failure 

### ISSUE THREAD

**Issue by Neilridley** [mriscoc/Ender3V2S1#223] opened 2022-07-16 12:04 UTC
Tried setting probe number to 1 and probing failed, high speed mode in ticked, was deploying probe without lifting Z axis, Ender S1 on F1 chip

**Comment by BytewaveMLP** [comment] 2022-07-16 17:31
Can reproduce on Ender 3 V2, Creality 422 mainboard.

**Comment by mriscoc** [comment] 2022-07-16 17:32
Thank you for you report. I didn't try with 1 (my mistake) but 0, means no multiprobe, then only one probe. 2 means two probe plus one extra to discard the fartest from mean value.

Setting to one not has a meaning, because it is not posible to do an average to do the comparison with the extra probing.

So, one is a forbidden setting.

**Comment by Neilridley** [comment] 2022-07-16 18:06
No problem I’ll keep it on 2

**Comment by mriscoc** [comment] 2022-08-17 18:40
Fixed in the latest version.

**Closed as completed by mriscoc** 2022-08-17 18:40 UTC
Labels: bug: Confirmed, known issue
