### ISSUE TITLE
S1 F4 ABL Failed

### ISSUE THREAD

**Issue by mpohoda** [mriscoc/Ender3V2S1#621] opened 2023-01-05 12:26 UTC
S1 F4 ABL mesh level 9x9, 8x8 every time finish in half of probing with fail and start again.

**Comment by mriscoc** [comment] 2023-01-05 12:35
Duplicate of: https://github.com/mriscoc/Ender3V2S1/issues/594

**Closed as not planned by mriscoc** 2023-01-05 12:35 UTC
Labels: duplicate
