### ISSUE TITLE
Ender 3 s1 mesh leveling issue 

### ISSUE THREAD

**Issue by ajwalk2008** [mriscoc/Ender3V2S1#666] opened 2023-01-21 14:54 UTC
I’ve been using the 6x6 on the newest update for f103 and lastnight I received a printer kill error when it got to step 31 in the mesh

**Comment by mriscoc** [comment] 2023-01-23 00:19
Duplicate of #594, #485, #203, #32 and #85

**Closed as completed** 2023-01-25 16:38 UTC
Labels: duplicate
