### ISSUE TITLE
[BUG?] SKR Mini E3 V3 crashes if 5th stepper driver is added in UART mode

### ISSUE THREAD

**Issue by RoP09** [mriscoc/Ender3V2S1#334] opened 2022-08-30 18:35 UTC
**Describe the bug**
The SKR Mini E3 V3 crashes if 5th TMC2209 stepper is added in UART mode.

Configuring the 5th TMC2209 in standalone mode works fine using the same pins, but once I set it to standalone the FW reboots endlessly after startup (immediately after the main control screen becomes visible, cannot rotate the knob or see the FW name scrolling into the view yet).

**To Reproduce**
Configuration used:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/82153569/187516080-aaa7dc1f-8eb2-45e2-a9d7-f4b4105cf383.png">

<img width="230" alt="image" src="https://user-images.githubusercontent.com/82153569/187516557-ffbc7835-a759-482c-891b-af39c5e6c636.png">

**Expected behavior**
TMC 2209 also should work in UART mode

 
**Version (please complete the following information):**
Latest config from special version (self compiled):
Recv: FIRMWARE_NAME:Marlin 2.1.0.1 MRiscoC Ender3V2-SKRME3V3-BLTUBL-T13-LA, based on bugfix-2.1.x (Aug 29 2022 09:45:14) SOURCE_CODE_URL:github.com/mriscoc/Ender3V2S1 PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender3V2-SKRME3V3-BLTUBL-T13-LA EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

**Additional context**
Not sure if this is a bug or wrong configuration, as I cannot find any software serial settings for that board (not supported at all?). All other steppes use hardware serial it seems.

**Comment by mriscoc** [comment] 2022-08-30 21:30
Please, first test your configuration with the latest Bugfix source code from Marlin repository. That could be a problem with Marlin core.

**Comment by RoP09** [comment] 2022-08-31 06:30
You mean the one from BTT here? 
https://github.com/bigtreetech/Marlin/tree/SKR-mini-E3-V3.0-G0B1

Or official Marlin?

Sorry not really used to compiling Marling - when I copy over the latest src and lib files from the official Marlin 2.1.x bugfix I am getting compilation errors for the custom_gcodes.cpp and others...

**Comment by mriscoc** [comment] 2022-08-31 16:30
Oficial Marlin Bugfix 2.1.x with the same configuration files.

**Comment by RoP09** [comment] 2022-08-31 18:32
Seems I broke my board now with this :(

Copied over the following files to the official Marlin 2.1.x bugfix and compiled fine, but after flashing the screen stays black:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/82153569/187753293-872f7d33-064a-41b8-a97d-8ed8e42983d1.png">

After flashing back to your FW, the screen also stays black now .. any suggestions?
(Still, seems the FW is  getting flashed, since the .bin file on the SD disappears and the firmware.CUR file is created by the printer)

-

UPDATE: I now flashed the FW version from the BTT Git here https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/V3.0/Marlin/firmware-ender3-bltouch-for-z-homing.bin

and at least now the printer comes back up (Octoprint connects), but the LCD still stays black...

UPDATE2: After flashing again the mriscoc based FW (renaming the file to capital letters FIRMWARE.BIN - i read elsewhere) the printer now finally came up with screen active --- will not try this again for now sorry :/

**Comment by mriscoc** [comment] 2022-08-31 19:34
Ok, thanks for trying.
Your issue seems to be something that needs to be fixed on the Marlin side, I don't have a SKR to try to fix.
Could be a problem with the pins assigned to the additional driver.

**Comment by mriscoc** [comment] 2022-08-31 19:37
Because it is not a problem with the Professional firmware with default configuration, I'm closing this issue by now, it will be re-opened if this configuration is confirmed to works with the current Marling bugfix branch.

**Comment by RoP09** [comment] 2022-08-31 19:38
Also thought the pins. But the behavior is the same If i use other pins in the board.

**Closed as completed by mriscoc** 2022-08-31 19:37 UTC
Labels: Bug: Potential ?

**Comment by RoP09** [comment] 2022-09-05 05:45
Did another try with setting  the configuration to **MSerial5** instead of the RX/TX pin config. Now the printer does not reboot, but shows a message "**TMC_CONNECTION_ERROR**" when booted up.

With manual control I can even move the 2nd Z stepper now, but it seems in this situation it somehow works half speed of the 1st stepper, so I went back to step/dir mode.

Seems something is still wrong either in wiring or in the configuration of those TMC2209s in UART mode.

Any ideas?

**Comment by mriscoc** [comment] 2022-09-05 06:13
https://3dprintingspace.com/u/sts41
https://marlinfw.org/docs/gcode/M122.html
https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.3/Wiring%20diagram/SKR%20V1.3-TMC2208-UART-Mode.png

Also, don't forget to disable the +V if you connect your board trough USB.

**Comment by RoP09** [comment] 2022-09-05 08:21
Thanks! Will give that M122 a try, forgot about it ...

The V+ I think is not an issue on the SKR boards, there is a jumper to set USB voltage supply which is not set.

**Comment by RoP09** [comment] 2022-09-05 17:52
<img width="289" alt="image" src="https://user-images.githubusercontent.com/82153569/188497498-a1d473f6-e728-489a-b4a3-e124b2e2cd95.png">

**Comment by mriscoc** [comment] 2022-09-06 03:11
It seems like a problem with the jumpers/connections of that driver.

**Comment by RoP09** [comment] 2022-09-06 13:42
Swapped Z2 with Y now and connected Y to the external driver in standalone, only solution that works it seems...
LIN_ADVANCE should still work as long as E0 is in UART mode, right?

**Comment by mriscoc** [comment] 2022-09-06 15:04
Currently Linear Advance also works with drivers in standalone mode.
