### ISSUE TITLE
[BUG] Ender3S1 Reboots and loses setting when SD card is inserted

### ISSUE THREAD

**Issue by WeededMedeusa** [mriscoc/Ender3V2S1#1260] opened 2024-02-21 01:59 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

As title states, when SD card is inserted in S1, machine reboots and all settings are lost

### Bug Timeline

Last update, not blatest

### Expected behavior

Not reboot

### Actual behavior

Rebooted

### Steps to Reproduce

Insert SD card

### Version of Professional Firmware

20240122

### Printer model

S1

### Electronics

Stock

### LCD/Controller

Stock

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Cura

**Comment by Vitorleoron** [comment] 2024-02-24 17:48
I have this problem here too, but mine is an Ender 3 V2, when I turn off the printer and power on the bed mesh settings reset to the default. Other settings are stored as Z-offset!

**Comment by mriscoc** [comment] 2024-02-26 00:48
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/1185

**Closed as completed by mriscoc** 2024-02-26 00:48 UTC
Labels: duplicate
