### ISSUE TITLE
Mesh viewer screen broken with TJC display unit.

### ISSUE THREAD

**Issue by adamr500** [mriscoc/Ender3V2S1#986] opened 2023-07-10 15:44 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I installed the professional firmware on my Ender 3 s1 F4 and tried out the mesh leveling. I the printer began probing the bed and no values showed up on the mesh points. I let it finish the leveling and then went to the mesh viewer. When i pressed on view mesh nothing happened for about 10 seconds and the screen froze. When it finally displayed the bed mesh there were random lines everywhere and still no values were on the points. I Adjusted the knobs based of the colour of the mesh points and tried again. The same issue occurred were no values would appear and when I opened the mesh viewer the lines were still there. I also took photos of the the mesh screen after the first and second bed mesh and they had identically coloured points.
 
![IMG_3607](https://github.com/mriscoc/Ender3V2S1/assets/127554141/c25069fb-5d06-49b8-9ea3-fcbbfb5c25cc)

### Bug Timeline

This bug happened the first time I used the firmware.

### Expected behavior

I expected there to be values on each point and the bed mesh to update every time I adjusted the bed.

### Actual behavior

There were no values on the mesh points, the bed mesh didn't update after being adjusted and there were random lines everywhere

### Steps to Reproduce

1 Turn on the machine
2 Go to 'automatic bed mesh' under prepare and press it
3 When the bed mesh is complete go to the 'bed mesh' viewer under 'advanced' and select

### Version of Professional Firmware

20230522

### Printer model

Creality Ender 3 s1 F4

### Electronics

Default board

### Add-ons

none

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment] 2023-07-10 16:38
Duplicate of #728 
Duplicate of #542

**Closed as completed by mriscoc** 2023-07-10 16:38 UTC
Labels: duplicate
