### ISSUE TITLE
homing after power out

### ISSUE THREAD

**Issue by liamwerk7676** [mriscoc/Ender3V2S1#698] opened 2023-01-29 15:49 UTC
**Describe the bug**
power went out it wanted to resume and it preheated and then gone to the point of the print and started to auto home a normal auto home not a xy auto home it homed z 2

**To Reproduce**
1.power out
2.continue

**Expected behavior**
home x and y and continue print

**Screenshots**

**Version (please complete the following information):**
Firmware version and release date
20221222
**Additional context**
print took a loong time so this was terible and used up a lot of filament

**Comment by mriscoc** [comment] 2023-01-29 15:59
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/571

**Comment by liamwerk7676** [comment] 2023-01-29 16:00
no it literly homed it dit not continue printing

**Comment by mriscoc** [comment] 2023-01-30 05:20
Closed because it is a duplicate of https://github.com/mriscoc/Ender3V2S1/issues/571

**Closed as completed by mriscoc** 2023-01-30 05:20 UTC
