### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by alsahime** [mriscoc/Ender3V2S1#939] opened 2023-05-31 20:27 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Unfortunately, I'm experiencing an error in the software. Can someone help me?

I have installed Mriscoc's firmware for Ender 3 V2 with BTT SKR MINI E3 V3, but when I try to heat it up, I receive a preheat error. The heating process is very slow and it gives this error before completion. I'm also encountering the same error during the PID test, and as a result, I am unable to print anything. I am not skilled in custom software development. Can anyone assist me with this?

### Bug Timeline

new

### Expected behavior

Unfortunately, I'm experiencing an error in the software. Can someone help me?

I have installed Mriscoc's firmware for Ender 3 V2 with BTT SKR MINI E3 V3, but when I try to heat it up, I receive a preheat error. The heating process is very slow and it gives this error before completion. I'm also encountering the same error during the PID test, and as a result, I am unable to print anything. I am not skilled in custom software development. Can anyone assist me with this?

### Version of Professional Firmware

Marlin 2.1.0.1 MRiscoC Ender3V2-SKRME3V3-BLTUBL, based on bugfix-2.1.x (Aug 16 2022 20:36:05) SOURCE_CODE_URL:github.com/mriscoc/Ender3V2S1 PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender3V2-SKRME3V3-BLTUBL EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Printer model

ender 3 v2

### Electronics

skr mini e3 v3

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment] 2023-05-31 22:32
Duplicate of https://github.com/mriscoc/Ender3V2S1/discussions/923#discussioncomment-6053640

**Closed by mriscoc** 2023-05-31 22:32 UTC
Labels: invalid
