### ISSUE TITLE
[BUG] Serveral issues with Ender3S1-F1-UBL-MPC-20230809

### ISSUE THREAD

**Issue by Horgul123** [mriscoc/Ender3V2S1#1052] opened 2023-08-26 10:11 UTC
### Did you test with a precompiled firmware?

No, but I will test it now!

### Bug Description

When using the Ender3S1-F1-UBL-MPC-20230809 FW I have several problems:
The issue with the filament sensor is "fixed" with changing the setting to "LOW", but:
- sometimes I get the message that there is a heating problem and the print is paused. After reheating everything works again for a while
- Got messages like Nozzle moved to home without a reason and the print is paused

Going back to the 202305 FW fixes all problems, so it must be 202308 related.
Can't be reproduced because it happens not always and not always at the same time of of the print

### Bug Timeline

new

### Expected behavior

Work like previous version 202305

### Actual behavior

Strange errors:
Heating suddenly stopped
Nozzel moved to home and print is stopped

Going back to Ender3S1-F1-UBL-MPC-20230522B solves the problems

### Steps to Reproduce

starting  print

### Version of Professional Firmware

Ender3S1-F1-UBL-MPC-20230809

### Printer model

Ender3 S1 F1

### Electronics

?

### Add-ons

none

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by twiggs462** [comment] 2023-09-01 03:15
I can confirm that these issues exist. I flashed the Ender3S1-F1-UBL-MPC-20230809 FW as well and I get random actions on first layer where the head moves to back right corner of bed and reverses filament out. With no warning or reason why. I am testing a print on previous version.

**Comment by Horgul123** [comment] 2023-09-01 05:31
@jderosa3 Thanks for confirming! I was not sure if this is a problem on my side or a real bug.

**Comment by twiggs462** [comment] 2023-09-01 14:04
No problem. Others have confirmed same issue on other forums as well.

**Comment by mriscoc** [comment] 2023-09-01 15:11
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/0aa35226-35b7-4720-be5f-7f7810a67925)

**Comment by mriscoc** [comment] 2023-09-01 15:12
Duplicate of: https://github.com/mriscoc/Ender3V2S1/issues/1025

**Closed as completed by mriscoc** 2023-09-01 15:11 UTC

**Comment by twiggs462** [comment] 2023-09-01 15:20
> https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides ![image](https://user-images.githubusercontent.com/2745567/265059553-0aa35226-35b7-4720-be5f-7f7810a67925.png)

I have a run-out sensor and still got this error when active and sensor working fine.

**Comment by Horgul123** [comment] 2023-09-01 15:40
@mriscoc Sorry, I don't understand your hint. I saw the bug with the filament sensor and set it to "low". as @jderosa3 said, even with sensor and correct setting I got the error. There is sometimes no error message, the printer just behaves strange.
With the wrong setting for the sensor I get a filament error message. But now there is no filament related message, the printer just stoppes (sometime swith the message, that there is a heating issue, sometimes without any message)

I have a stock S1, so your config guide tells me, nothing needs to be changed

**Comment by mriscoc** [comment] 2023-09-01 17:05
> I flashed the Ender3S1-F1-UBL-MPC-20230809 FW as well and I get random actions on first layer where the head moves to back right corner of bed and reverses filament out.

Read the Wiki (manual) and follow the [guide about filament sensor](https://github.com/mriscoc/Ender3V2S1/wiki/Filament-Settings-Menu#run-out-sensor).

**Comment by mriscoc** [comment] 2023-09-01 17:27
> I have a run-out sensor and still got this error when active and sensor working fine.

You need to found the correct High/Low configuration that match your filament sensor.

**Comment by Horgul123** [comment] 2023-09-01 18:33
@mriscoc : in my case I don't get a filament error when setting it to LOW. I get errors regarding a heating problem or without an error. This doesn't look like the filament sensor is the reason

**Comment by mriscoc** [comment] 2023-09-01 19:07
@Horgul123 Heating is not related to the filament runout sensor.

**Comment by mriscoc** [comment] 2023-09-01 19:13
> No problem. Others have confirmed same issue on other forums as well.

@jderosa3 your heating issue is not related to the runout sensor, check your thermistor and heatblock silicone jacket.

I can't reproduce your heating issue.

**Comment by Horgul123** [comment] 2023-09-02 08:09
This is what we're saying. But it only happens with your latest firmware. With
the older one everything works, so it can't be a hardware issue.
If there is anything I can do to help you to find the root cause let me know.
I tried it twice with the new new version and had the same issues. When I reinstalled the old version it was ok again

**Comment by mriscoc** [comment] 2023-09-03 02:49
I need reproducible steps to be able to debug any possible bug. You are printing from SD or from a host (Octoprint)

**Comment by Horgul123** [comment] 2023-09-03 06:08
I'm printing via Octoprint.
It happens shortly after starting a print. I'll install the new version
again today and document everything in detail

**Comment by Horgul123** [comment] 2023-09-03 15:56
Checked it again as promised.
With "LOW" the print stopped after the first layer, purged some material and told me "Nozzle parked".
With "HIGH" it's working. Last time I had issues with this setting, too.

**Comment by mriscoc** [comment] 2023-09-04 12:34
> I'm printing via Octoprint. It happens shortly after starting a print. I'll install the new version again today and document everything in detail

Did you disable the +VUSB?

**Comment by Horgul123** [comment] 2023-09-04 12:59
@mriscoc no, didn't do this. It works fine.

At the moment it works with your latest FW, too. No idea, why it made problems a few days ago..... Did the same as yesterday.

**Comment by mriscoc** [comment] 2023-09-04 13:01
Remove the +VUSB, it causes random behaviors and might damage the control board.
https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#important

**Comment by Horgul123** [comment] 2023-09-04 13:46
As mentioned: The printer runs fine. I use a network USB extention, so I don't think the pin is powered. I'll double check this
