### ISSUE TITLE
Multiple probing ingores a value of 1

### ISSUE THREAD

**Issue by AgenB** [mriscoc/Ender3V2S1#347] opened 2022-09-01 22:16 UTC
**Describe the bug**
When I try to change the default multiple probing amount from 2 (which results in 3 probes per point) to 1, it changes to 0 by itself, resulting in just 1 probe per point, can't set it to 2.

**To Reproduce**
1. Go to Advanced settings -> Probe settings
2. Set Multiple Probing to 1, it changes to 0 after you reopen the menu.

**Version:**
Ender 3 v2 4.2.2 BLT UBL 20220816

**Comment by mriscoc** [comment] 2022-09-01 22:40
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/319

**Closed as completed by mriscoc** 2022-09-01 22:40 UTC

**Comment by classicrocker883** [comment] 2022-09-03 08:40
@AgenB 

(line ~2290 in file proui/dwin.cpp)

void ApplyProbeMultiple() { PRO_data.multiple_probing = (MenuData.Value > 0) ? MenuData.Value : 0; }

change the value to be greater than 0 rather than 1.

so if you later choose muliprobing in the menu, a zero value would make 1 time slow probe.
value of 1 will make 2 probes, 1 fast and 1 slow.
each one adds one. it is basically ADDING probes rather than MULTIPLE probes

**Comment by mriscoc** [comment] 2022-09-03 15:39
> @AgenB
> 
> (line ~2290 in file proui/dwin.cpp)
> 
> void ApplyProbeMultiple() { PRO_data.multiple_probing = (MenuData.Value > 0) ? MenuData.Value : 0; }
> 
> change the value to be greater than 0 rather than 1.
> 
> so if you later choose muliprobing in the menu, a zero value would make 1 time slow probe. value of 1 will make 2 probes, 1 fast and 1 slow. each one adds one. it is basically ADDING probes rather than MULTIPLE probes

Be aware that is not correct, PRO_data.multiple_probing must be forced to 0 for any value lower than 2.
