### ISSUE TITLE
Screen shows distorted UI Artifacts while printing.

### ISSUE THREAD

**Issue by gorillale** [mriscoc/Ender3V2S1#749] opened 2023-02-20 09:57 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

What this for hyroglyphs

### Steps to Reproduce

Print object

### Version of Professional Firmware

2.2.1

### Printer model

ender 3v2

### Electronics

4.2.2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Repetier Host

### Additional information & file uploads

![20230220_105022](https://user-images.githubusercontent.com/87060392/220072529-6fe1f923-9d0e-4138-9293-800efa8020ba.jpg)

**Comment by gorillale** [comment] 2023-02-20 10:58
I used firmware 2022 10 02 and see this after update Repetier Host Pro 1.4.8
I will try the 20221222 now

**Comment by mriscoc** [comment] 2023-02-24 00:15
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/359

**Comment by mriscoc** [comment] 2023-02-24 00:15
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/328

**Comment by mriscoc** [comment] 2023-03-13 05:17
Closed as duplicate

**Closed as completed by mriscoc** 2023-03-13 05:17 UTC
