### ISSUE TITLE
Ender 3v2 reboots with some µSD cards

### ISSUE THREAD

**Issue by Slavikpd** [mriscoc/Ender3V2S1#679] opened 2023-01-25 17:08 UTC
Good day. I have an Ender 3v2 main board 4.2.2. After updating the latest firmware version Ender3V2-422-BLTUBL-MPC-20221222.bin
it happens to me that the printer restarts itself before printing. It also happened that the picture fell apart and I had to turn it off. And it also happens that some layers are damaged. Can you advise me where the problem might be. The previous firmware version did not do this. Well thank you.

![327455911_853225942439366_6354314794678194017_n](https://user-images.githubusercontent.com/99100274/214632074-3389658c-8460-4a9b-8ffa-946ea6b751a6.jpg)

**Comment by giacomoferretti** [comment] 2023-02-11 16:03
Also happening to me. If I turn on the printer with the SD card inserted, the printer will restart until I remove the SD card.

**Comment by Slavikpd** [comment] 2023-02-11 17:48
ThankYou


Dňa so 11. 2. 2023, 17:03 Giacomo Ferretti ***@***.***>
napísal(a):

**Comment by mriscoc** [comment] 2023-02-13 16:20
> Also happening to me. If I turn on the printer with the SD card inserted, the printer will restart until I remove the SD card.

Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/480

**Comment by giacomoferretti** [comment] 2023-02-13 16:29
> > Also happening to me. If I turn on the printer with the SD card inserted, the printer will restart until I remove the SD card.
> 
> Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/480

Thanks, didn't see that.

**Comment by Slavikpd** [comment] 2023-02-16 14:11
I returned the previous firmware version because I upgraded the extruder on
a split extruder. I'm done with it, so I'll try the latest version again.

po 13. 2. 2023 o 17:20 Miguel Risco-Castillo ***@***.***>
napísal(a):

**Comment by J-oe-rg** [comment] 2023-02-26 17:57
Hi Miguel, I have the same issue reported in https://github.com/mriscoc/Ender3V2S1/issues/480 's first posting.

Original Creality 8GB Card formatted with FAT32, 4096 byte cluster size.
Doesn't matter if there are files on the card or not. Media update is off.

For me that issue did not occur before on stock or Jyers firmware. (There was an assumption by another user.)

By the way, last firmware update was made with this card but I formated it afterwards.
A second card 16GB Samsung doesn't have that issue. Next release I will update with that card to see if there is some coincidence.

Printer: Ender 3 V2, board 4.2.2
Firmware: Ender3V2-422-MM-MPC-20221222.bin

**Workaround:** Just take out the card for some seconds and put it in again. Boot loop stops.

Thank you for the great firmware!

**Comment by mriscoc** [comment] 2023-03-13 05:36
Please test with latest version.

**Comment by J-N-R** [comment] 2023-03-30 04:09
I'm getting it too. Frozen on startup

Printer: Ender 3 V2, board 4.2.2
Firmware: Ender3V2-422-BLTUBL-MPC-20230312.bin

**Comment by mriscoc** [comment] 2023-03-31 03:51
Closed as duplicate

**Closed as completed by mriscoc** 2023-03-31 03:51 UTC
Labels: bug: False alarm?

**Comment by J-N-R** [comment] 2023-04-03 05:11
Any update on this? All the duplicate bugs are closed but its still freezing using the given 8gb card (FAT32 formatted)

**Comment by mriscoc** [comment] 2023-04-08 22:33
Informative link: https://www.3dprintgorilla.com/ender-3-pro-v2-neo-s1-sd-card-size
