### ISSUE TITLE
[BUG] BL touch fails to deploy on 62/64 grid measurement causing head to crash into bed

### ISSUE THREAD

**Issue by mikld86** [mriscoc/Ender3V2S1#783] opened 2023-03-11 00:50 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I always run a 64 point measurement for BL touch. 
I normally walk away and let it do its thing. 
Today I stayed and watched.
As I watched, at point 62 or 63 the BL touch failed to deploy, causing the head to crash into the print bed. 

### Expected behavior

BL touch to deploy

### Actual behavior

BL touch failed to deploy

### Version of Professional Firmware

2.1.3

### Printer model

Ender 3 S1

### Add-ons

None

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment] 2023-03-11 01:55
Check the wiki notes about CRTouch you must disable HS mode for meshes larger than 5x5

Duplicate of: https://github.com/mriscoc/Ender3V2S1/issues/594, https://github.com/mriscoc/Ender3V2S1/issues/485, https://github.com/mriscoc/Ender3V2S1/issues/285, https://github.com/mriscoc/Ender3V2S1/issues/203, https://github.com/mriscoc/Ender3V2S1/issues/85, https://github.com/mriscoc/Ender3V2S1/issues/32

**Comment by mikld86** [comment] 2023-03-11 04:29
Thanks for pointing me to that solution.

**Closed as completed** 2023-03-11 05:50 UTC
Labels: duplicate, bug: False alarm?
