### ISSUE TITLE
could not find one of 'package.json' manifest files in the package

### ISSUE THREAD

**Issue by karlc28** [mriscoc/Ender3V2S1#463] opened 2022-10-24 16:56 UTC
When trying to build the firmware I get an error
could not find one of 'package.json' manifest files in the package
![2D8B7614-520C-4076-A595-D831CA95032B](https://user-images.githubusercontent.com/92265354/197582590-a851ff3c-c24c-48f9-8222-e2ff57c798aa.jpeg)

**Comment by mriscoc** [comment] 2022-10-24 17:39
Duplicate of: https://github.com/mriscoc/Ender3V2S1/discussions/379

**Closed as completed by mriscoc** 2022-10-24 17:39 UTC

**Comment by karlc28** [comment] 2022-10-24 20:05
So reinstalled vs code and now that’s fixed but now have this issue 
I’m using the configuration.h file from the linear advance source code
![image](https://user-images.githubusercontent.com/92265354/197618387-e42a1d91-71df-491c-afa8-485d94f3c4ed.jpg)
