### ISSUE TITLE
[BUG] Issue with displaying saved bed mesh 

### ISSUE THREAD

**Issue by bauch1234** [mriscoc/Ender3V2S1#1004] opened 2023-07-27 12:40 UTC
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Ender 3 S1 F4 tjc screen displays this when viewing a bed mesh that was saved 

i saw something in another bug report about needing to update firmware so i updated screen firmware from here 

https://github.com/mriscoc/Ender3V2S1/blob/Ender3V2S1-Released/display%20assets/tjc_update.zip?raw=true

had no effect

i also tired compiling my own firmware from the configurator and it would fail to compile with the f401rc witch is my soc only the f401re would work but the firmware wouldnt load on my printer ( i know you dont provide support on that but just saying)

### Expected behavior

to display normally like when the mesh was created

### Actual behavior

look at attached picture

### Steps to Reproduce

simply open a saved mesh 

### Version of Professional Firmware

precompiled Ender3S1-F4-UBL-20230522B.

### Printer model

s1

### Electronics

f401rc

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

![357344655_612701080996756_8880516971029177663_n](https://github.com/mriscoc/Ender3V2S1/assets/5841064/c9dfdc1c-8bcc-4f1a-9db4-ba75486d96c4)

**Comment by mriscoc** [comment] 2023-07-27 17:47
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/986
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/728
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/542

Check from the listed posts how to resolve your issue.

**Closed as completed by mriscoc** 2023-07-27 17:47 UTC
Labels: duplicate
